// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: And-E_DisplayUI

#ifndef _UI_COMP_BUTTON1_H
#define _UI_COMP_BUTTON1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button1
#define UI_COMP_BUTTON1_BUTTON1 0
#define _UI_COMP_BUTTON1_NUM 1
lv_obj_t * ui_Button1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
