// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: And-E_DisplayUI

#include "../ui.h"

lv_obj_t * uic_StartImage;
lv_obj_t * uic_SettingsImage;
lv_obj_t * uic_SettingsButton;
lv_obj_t * uic_InfoImage;
lv_obj_t * uic_InfoButton;
lv_obj_t * uic_AndEImage;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_AndEImage = NULL;
lv_obj_t * ui_Buttons = NULL;
lv_obj_t * ui_InfoButton = NULL;
lv_obj_t * ui_InfoImage = NULL;
lv_obj_t * ui_SettingsButton = NULL;
lv_obj_t * ui_SettingsImage = NULL;
lv_obj_t * ui_StartButton = NULL;
lv_obj_t * ui_StartImage = NULL;
// event funtions
void ui_event_InfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_StartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x1A6EC5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AndEImage = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_AndEImage, &ui_img_945321139);
    lv_obj_set_width(ui_AndEImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AndEImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AndEImage, 0);
    lv_obj_set_y(ui_AndEImage, -39);
    lv_obj_set_align(ui_AndEImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AndEImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AndEImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_AndEImage, 80);

    ui_Buttons = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Buttons, 328);
    lv_obj_set_height(ui_Buttons, 187);
    lv_obj_set_x(ui_Buttons, 0);
    lv_obj_set_y(ui_Buttons, 1);
    lv_obj_set_align(ui_Buttons, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Buttons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttons, lv_color_hex(0x575757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Buttons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Buttons, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoButton = lv_button_create(ui_Buttons);
    lv_obj_set_width(ui_InfoButton, 103);
    lv_obj_set_height(ui_InfoButton, 92);
    lv_obj_set_x(ui_InfoButton, 104);
    lv_obj_set_y(ui_InfoButton, 44);
    lv_obj_set_align(ui_InfoButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InfoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_InfoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InfoButton, lv_color_hex(0xC44DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_InfoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_InfoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_InfoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoImage = lv_image_create(ui_InfoButton);
    lv_image_set_src(ui_InfoImage, &ui_img_686816875);
    lv_obj_set_width(ui_InfoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InfoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InfoImage, 12);
    lv_obj_set_y(ui_InfoImage, 0);
    lv_obj_set_align(ui_InfoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InfoImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_InfoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_InfoImage, 310);

    ui_SettingsButton = lv_button_create(ui_Buttons);
    lv_obj_set_width(ui_SettingsButton, 103);
    lv_obj_set_height(ui_SettingsButton, 92);
    lv_obj_set_x(ui_SettingsButton, -106);
    lv_obj_set_y(ui_SettingsButton, 44);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsButton, lv_color_hex(0xC44DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SettingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsImage = lv_image_create(ui_SettingsButton);
    lv_image_set_src(ui_SettingsImage, &ui_img_1471171794);
    lv_obj_set_width(ui_SettingsImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsImage, -13);
    lv_obj_set_y(ui_SettingsImage, 0);
    lv_obj_set_align(ui_SettingsImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SettingsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StartButton = lv_button_create(ui_Buttons);
    lv_obj_set_width(ui_StartButton, 103);
    lv_obj_set_height(ui_StartButton, 92);
    lv_obj_set_x(ui_StartButton, 1);
    lv_obj_set_y(ui_StartButton, 44);
    lv_obj_set_align(ui_StartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_StartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartButton, lv_color_hex(0xC44DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StartButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_StartButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_StartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_StartButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_StartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartImage = lv_image_create(ui_StartButton);
    lv_image_set_src(ui_StartImage, &ui_img_836209702);
    lv_obj_set_width(ui_StartImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartImage, 1);
    lv_obj_set_y(ui_StartImage, 0);
    lv_obj_set_align(ui_StartImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_StartImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_InfoButton, ui_event_InfoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartButton, ui_event_StartButton, LV_EVENT_ALL, NULL);
    uic_AndEImage = ui_AndEImage;
    uic_InfoButton = ui_InfoButton;
    uic_InfoImage = ui_InfoImage;
    uic_SettingsButton = ui_SettingsButton;
    uic_SettingsImage = ui_SettingsImage;
    uic_StartImage = ui_StartImage;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_AndEImage = NULL;
    ui_AndEImage = NULL;
    ui_Buttons = NULL;
    uic_InfoButton = NULL;
    ui_InfoButton = NULL;
    uic_InfoImage = NULL;
    ui_InfoImage = NULL;
    uic_SettingsButton = NULL;
    ui_SettingsButton = NULL;
    uic_SettingsImage = NULL;
    ui_SettingsImage = NULL;
    ui_StartButton = NULL;
    uic_StartImage = NULL;
    ui_StartImage = NULL;

}
