// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: And-E_DisplayUI

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_ThrottleBar;
extern lv_obj_t * ui_Throttle;
extern lv_obj_t * ui_BrakeBar;
extern lv_obj_t * ui_Brake;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Voltage;
extern lv_obj_t * ui_BatteryVoltage;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_MotorTemp;
extern lv_obj_t * ui_SpeedArc;
extern lv_obj_t * ui_CurrentSpeed;
extern lv_obj_t * ui_Speed;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ThrottleBar;
extern lv_obj_t * uic_Throttle;
extern lv_obj_t * uic_BrakeBar;
extern lv_obj_t * uic_Brake;
extern lv_obj_t * uic_Voltage;
extern lv_obj_t * uic_BatteryVoltage;
extern lv_obj_t * uic_Temp;
extern lv_obj_t * uic_MotorTemp;
extern lv_obj_t * uic_SpeedArc;
extern lv_obj_t * uic_CurrentSpeed;
extern lv_obj_t * uic_Speed;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

