// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: And-E_DisplayUI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_AndEImage;
extern lv_obj_t * ui_Buttons;
extern void ui_event_InfoButton(lv_event_t * e);
extern lv_obj_t * ui_InfoButton;
extern lv_obj_t * ui_InfoImage;
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_SettingsImage;
extern void ui_event_StartButton(lv_event_t * e);
extern lv_obj_t * ui_StartButton;
extern lv_obj_t * ui_StartImage;
// CUSTOM VARIABLES
extern lv_obj_t * uic_AndEImage;
extern lv_obj_t * uic_InfoButton;
extern lv_obj_t * uic_InfoImage;
extern lv_obj_t * uic_SettingsButton;
extern lv_obj_t * uic_SettingsImage;
extern lv_obj_t * uic_StartImage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

