// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: And-E_DisplayUI

#include "../ui.h"

lv_obj_t * uic_Info;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Info = NULL;
lv_obj_t * ui_Button1 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Info, lv_pct(90));
    lv_obj_set_height(ui_Info, lv_pct(72));
    lv_obj_set_x(ui_Info, -5);
    lv_obj_set_y(ui_Info, -23);
    lv_obj_set_align(ui_Info, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Info, "1\n2\n3\n4\n5\n5\nfgd\ngdf\ngfd\ngdfs\nfdgs\nHI\nfgd\nfgd\nf\ngds\nfgd\nfgd\nfgds\n");
    lv_obj_add_flag(ui_Info, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Info, LV_SCROLLBAR_MODE_ON);

    ui_Button1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 61);
    lv_obj_set_height(ui_Button1, 43);
    lv_obj_set_x(ui_Button1, 107);
    lv_obj_set_y(ui_Button1, 69);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    uic_Info = ui_Info;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    uic_Info = NULL;
    ui_Info = NULL;
    ui_Button1 = NULL;

}
