// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: And-E_DisplayUI

#ifndef _AND_E_DISPLAYUI_UI_H
#define _AND_E_DISPLAYUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_945321139);    // assets/And-E_AI.png
LV_IMG_DECLARE(ui_img_686816875);    // assets/icons8-info-48.png
LV_IMG_DECLARE(ui_img_1471171794);    // assets/icons8-settings-48.png
LV_IMG_DECLARE(ui_img_836209702);    // assets/icons8-start-button-64.png
LV_IMG_DECLARE(ui_img_1577682898);    // assets/icons8-home-24.png

// FONTS
LV_FONT_DECLARE(ui_font_Chokokutai);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
